version: "3"

services:
  broker_app:
    image: dius/pact-broker
    ports:
      - "80:80"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: sqlite
      PACT_BROKER_DATABASE_NAME: pact_broker.sqlite